import type { Metadata } from "next";
import "./globals.css";
import DashboardWithSidebar from "./components/shared/DashboardWithSidebar";

export const metadata: Metadata = {
  title: "NSR Tools",
  description: "Generated by NSR Dev",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <DashboardWithSidebar>
          {children}
        </DashboardWithSidebar>
      </body>
    </html>
  );
}